// Code generated by MockGen. DO NOT EDIT.
// Source: identity.go

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIdentityUtil is a mock of IdentityUtil interface.
type MockIdentityUtil struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityUtilMockRecorder
}

// MockIdentityUtilMockRecorder is the mock recorder for MockIdentityUtil.
type MockIdentityUtilMockRecorder struct {
	mock *MockIdentityUtil
}

// NewMockIdentityUtil creates a new mock instance.
func NewMockIdentityUtil(ctrl *gomock.Controller) *MockIdentityUtil {
	mock := &MockIdentityUtil{ctrl: ctrl}
	mock.recorder = &MockIdentityUtilMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityUtil) EXPECT() *MockIdentityUtilMockRecorder {
	return m.recorder
}

// NewId mocks base method.
func (m *MockIdentityUtil) NewId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewId")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewId indicates an expected call of NewId.
func (mr *MockIdentityUtilMockRecorder) NewId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewId", reflect.TypeOf((*MockIdentityUtil)(nil).NewId))
}
